### ISSUE TITLE
Bug: 404 Page Not Found on refreshing a page on gh-pages

### ISSUE THREAD

**Issue by catherineisonline** [catherineisonline/rest-countries#1]
When refreshing a page I get a 404 Page Not Found error. This happens because GitHub pages don't support single-page apps. It doesn't have access to front-end routes.  You can go back and forth without any issue until you refresh the page. I tested it in Chrome, Safari on iPhone, and MacBook Air M1.

![Alt Text](https://im4.ezgif.com/tmp/ezgif-4-453bd9c33a.gif)

Steps to reproduce the error:

1. Visit: https://catherineisonline.github.io/rest-countries/
2. Click on any country to be redirected to the single country page
3. Refresh the page

I have been researching this for almost a month and have not found any solution yet.

**Comment by msuwignyo** [comment]
I think this is because of how the CSR route mechanism behaves (it's perfectly normal).

The workaround is by creating a [custom 404 page](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site), and writing some javascript to redirect to the index.html.

Resource: [React app hosted as Github Project Page. How to display custom 404 page?](https://github.com/facebook/create-react-app/discussions/11938)

**Comment by catherineisonline** [comment]
> 

Thank you for the feedback. I believe that will be the best solution for now
